name: libnomp-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pip
  - cmake=3.24
  - symengine=0.10.1
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
  - clang-format=15.0.3
  - doxygen
