name: libnomp-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - cmake=3.24
  - python=3.10
  - gmp
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
  - clang-format=16
  - clang-tools=16
  - clangdev=16.0 # We need this since clang-tools don't install clang headers.
  - doxygen
