name: libnomp-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - cmake=3.22
  - pip
  - pip:
    - -r requirements.txt
    - isort==5.10.1
    - black==22.8.0
    - flake8==4.0.1
    - breathe==4.34.0
    - Sphinx==5.1.1
    - sphinx-rtd-theme==1.0.0
  - clang-format=15.0.3
  - doxygen
