#!/bin/bash

# script variables
: "${NOMP_INSTALL_DIR:="${HOME}/.nomp"}"
SOURCE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BUILD_DIR="${SOURCE_DIR}/build"
CMAKE_OPTS=("-DCMAKE_INSTALL_PREFIX=${HOME}/.nomp" "-DOpenCL_LIBRARY=/lib/x86_64-linux-gnu/libOpenCL.so.1")
VERBOSE=false
OUTPUT=""
CONFIGURE_SUCCESS=false
SCRIPT_PATH="${NOMP_INSTALL_DIR}/scripts"
NOMP_ENVIRONMENT=""

# colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
reset=$(tput sgr0)

function print_help() {
  echo -e "usage: ./lncfg [-h|--help] [-v|--verbose] [-d|--debug] [-D|--docs]\n" \
    "\t[-i|--install-dir <install directory>]\n\n" \
    "${cyan}-h/--help:${reset} Print help for libnomp configuration.\n" \
    "${cyan}-v/--verbose:${reset} Display all the build output.\n" \
    "${cyan}-d/--debug:${reset} Build with debug symbols.\n" \
    "${cyan}-D/--docs:${reset} Build with user documentation.\n" \
    "${cyan}-i/--install-dir:${reset} Specify installation directory for libnomp (Default: ${NOMP_INSTALL_DIR}).\n"
}

# create build directory if not exists
[[ ! -d "${BUILD_DIR}" ]] && mkdir build

# parse the options
while [ $# -gt 0 ]; do
  case $1 in
  -h | --help)
    print_help
    exit 0
    ;;
  -v | --verbose) VERBOSE=true ;;
  -d | --debug) CMAKE_OPTS+=("-DCMAKE_BUILD_TYPE=DEBUG") ;;
  -D | --docs) CMAKE_OPTS+=("-DENABLE_DOCS=ON") ;;
  -i | --install-dir) shift && NOMP_INSTALL_DIR="${1}" ;;
  *) echo "${red}Invalid argument: ${1}${reset}" &&
    echo "See ${cyan}./lncfg -h${reset} or ${cyan}./lncfg --help${reset} for the accepted commands" &&
    exit 1 ;;
  esac
  shift
done

# configure cmake
echo "Configuring build files for libnomp..."
cd "${BUILD_DIR}" &&
  OUTPUT+=$(cmake .. "${CMAKE_OPTS[@]}") &&
  CONFIGURE_SUCCESS=true

if [ "${CONFIGURE_SUCCESS}" = true ]; then
  [ "${VERBOSE}" = true ] && echo "${OUTPUT}"
  echo "${green}Successfully created build files for libnomp${reset}"
  echo "To install libnomp, execute '${cyan}cd ${SOURCE_DIR}/build && make install${reset}'"

  # set the install env variable if not set
  [[ -n "${NOMP_INSTALL_DIR}" ]] &&
    export "NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}" &&
    { grep -xFq "export NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}" ~/.bashrc ||
      NOMP_ENVIRONMENT="# setup nomp environment variables\nexport NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}\n"; }

  # add lnrun script to path
  [[ ${PATH} != *"${SCRIPT_PATH}"* ]] &&
    export "PATH=${SCRIPT_PATH}:${PATH}" &&
    { grep -xFq "export PATH=${SCRIPT_PATH}:\${PATH}" ~/.bashrc ||
      NOMP_ENVIRONMENT+="export PATH=${SCRIPT_PATH}:\${PATH}\n"; }

  [[ ${NOMP_ENVIRONMENT} ]] && echo -e "${NOMP_ENVIRONMENT}" >>~/.bashrc
  exit 0
else
  echo "${OUTPUT}"
  echo "${red}Failed to build libnomp${reset}"
  exit 1
fi
