#!/bin/bash

# script variables
NOMP_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOMP_BIN_PATH="${NOMP_INSTALL_DIR}/bin"
NOMP_DEFAULT_PROMPT=""
NOMP_LNSTATE_PATH="${NOMP_SOURCE_DIR}/.lnstate"

# colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
reset=$(tput sgr0)

# read state variables of lncfg
if [[ -f "${NOMP_LNSTATE_PATH}" ]]; then
  source "${NOMP_LNSTATE_PATH}"
else
  echo "${red}You should run ./lncfg before running ./lninstall${reset}"
  exit 1
fi

function update_bashrc() {
  echo -e "${NOMP_ENVIRONMENT}" >>~/.bashrc &&
    echo "${green}Successfully exported variables to .bashrc${reset}" &&
    exit 0
}

# check for default prompt
if [[ $# -gt 0 ]]; then
  case $1 in
  --yes) NOMP_DEFAULT_PROMPT="y" ;;
  --no) NOMP_DEFAULT_PROMPT="n" ;;
  esac
fi

# installing libnomp
NOMP_INSTALL_SUCCESS=false
cd "${NOMP_BUILD_DIR}" &&
  make install &&
  NOMP_INSTALL_SUCCESS=true

if [[ ${NOMP_INSTALL_SUCCESS} = true ]]; then
  echo "${green}Successfully installed libnomp${reset}"
  echo "See ${cyan}lnrun -h${reset} or ${cyan}lnrun --help${reset} for available commands"

  NOMP_ENVIRONMENT=""
  [[ -n ${NOMP_INSTALL_DIR} ]] &&
    { grep -xFq "export NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}" ~/.bashrc ||
      NOMP_ENVIRONMENT="# Setup nomp environment variables\nexport NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}\n"; }

  # add lnrun script to path
  [[ ${PATH} != *"${NOMP_BIN_PATH}"* ]] &&
    { grep -xFq "export PATH=${NOMP_BIN_PATH}:\${PATH}" ~/.bashrc ||
      NOMP_ENVIRONMENT+="export PATH=${NOMP_BIN_PATH}:\${PATH}\n"; }

  # set the install env variable if not
  if [[ -n ${NOMP_ENVIRONMENT} ]]; then
    [[ ${NOMP_DEFAULT_PROMPT} = "y" ]] && update_bashrc
    [[ ${NOMP_DEFAULT_PROMPT} = "n" ]] && exit 0
    while :; do
      read -p "Do you wish to add libnomp variables to .bashrc? [Y|n]: " -n 1 -r
      echo
      [[ $REPLY =~ ^[Yy]$ ]] && update_bashrc
      [[ $REPLY =~ ^[Nn]$ ]] && exit 0
    done
  fi
else
  echo "${red}Failed to install libnomp${reset}"
fi

cd "${NOMP_SOURCE_DIR}" || exit 0
