#!/bin/bash

# colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
reset=$(tput sgr0)

# read state variables of lncfg
if [[ -f ".lnstate" ]]; then
  source ".lnstate"
else
  echo "${red}You should run ./lncfg before running . lninstall${reset}"
  exit 1
fi
NOMP_SCRIPT_PATH="${NOMP_INSTALL_DIR}/scripts"

# installing libnomp
NOMP_INSTALL_SUCCESS=false
cd "${NOMP_SOURCE_DIR}/build" &&
  make install &&
  NOMP_INSTALL_SUCCESS=true

if [[ ${NOMP_INSTALL_SUCCESS} = true ]]; then
  echo "${green}Successfully installed libnomp${reset}"
  echo "See ${cyan}lnrun -h${reset} for available commands"

  NOMP_ENVIRONMENT=""
  [[ -n ${NOMP_INSTALL_DIR} ]] &&
    { grep -xFq "export NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}" ~/.bashrc ||
      NOMP_ENVIRONMENT="# Setup nomp environment variables\nexport NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}\n"; }

  # add lnrun script to path
  [[ ${PATH} != *"${NOMP_SCRIPT_PATH}"* ]] &&
    { grep -xFq "export PATH=${NOMP_SCRIPT_PATH}:\${PATH}" ~/.bashrc ||
      NOMP_ENVIRONMENT+="export PATH=${NOMP_SCRIPT_PATH}:\${PATH}\n"; }

  # set the install env variable if not
  if [[ -n ${NOMP_ENVIRONMENT} ]]; then
    while :; do
      read -p "Do you wish to add NOMP variables to .bashrc? [Y|n]: " -n 1 -r
      echo
      [[ $REPLY =~ ^[Yy]$ ]] &&
        echo -e "${NOMP_ENVIRONMENT}" >>~/.bashrc &&
        echo "${green}Successfully exported variables to .bashrc${reset}" &&
        exit 0
      [[ $REPLY =~ ^[Nn]$ ]] &&
        exit 0
    done
  fi
else
  echo "${red}Failed to install libnomp${reset}"
fi

cd "${NOMP_SOURCE_DIR}" || exit 0
