#!/bin/bash

# script variables
NOMP_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOMP_DEFAULT_PROMPT=""
NOMP_LNSTATE_PATH="${NOMP_SOURCE_DIR}/.lnstate"
NOMP_SHELL_CONFIG_FILE=""
PYLINT_CMD="pylint --fail-under=8.95 python/*.py tests/*.py"
FLAKE8_CMD="flake8 python/*.py tests/*.py"
CLANG_FORMAT_TEST_CMD="clang-format --dry-run --Werror src/*.[ch] tests/*.[ch]"
CLANG_FORMAT_CMD="clang-format -i src/*.[ch] tests/*.[ch]"
NOMP_SUPPORTED_FORMAT_CMDS=("${PYLINT_CMD}" "${FLAKE8_CMD}" "${CLANG_FORMAT_CMD}" "${CLANG_FORMAT_TEST_CMD}")

# colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
reset=$(tput sgr0)

# read state variables of lncfg
if [[ -f "${NOMP_LNSTATE_PATH}" ]]; then
  source "${NOMP_LNSTATE_PATH}"
elif [[ "${1}" != "f" && "${1}" != "format" ]]; then
  echo "${red}You should run ./lncfg before running ./${0}${reset}"
  exit 1
fi
NOMP_BIN_PATH="${NOMP_INSTALL_DIR}/bin"

# check the shell config file
if [[ -f ~/.bashrc ]]; then
  NOMP_SHELL_CONFIG_FILE="${HOME}/.bashrc"
elif [[ -f ~/.zshrc ]]; then
  NOMP_SHELL_CONFIG_FILE="${HOME}/.zshrc"
fi

function update_bashrc() {
  if [[ -n ${NOMP_SHELL_CONFIG_FILE} ]]; then
    echo -e "${NOMP_ENVIRONMENT}" >>"${NOMP_SHELL_CONFIG_FILE}"
    echo "${green}Successfully exported variables to" \
      "${NOMP_SHELL_CONFIG_FILE}${reset}."
  fi
  exit 0
}

function print_help() {
  echo -e " NAME\n\t Utility tools for installing and formatting libnomp.\n\n" \
    "INSTALL\n" \
    "\tlnmake i|install [--yes|--no]\n" \
    "\tInstall libnomp.\n\n" \
    "\t${cyan}-y${reset}, ${cyan}--yes${reset}" \
    "\tYes to all prompts.\n" \
    "\t${cyan}-n${reset}, ${cyan}--no${reset}" \
    "\tNo to all prompts.\n\n" \
    "FORMAT\n" \
    "\tlnmake f|format [--pylint] [--flake8] [--c] [--ctest]\n" \
    "\tFormat the source files of libnomp.\n" \
    "\tIf no arguments are provided, all source files are formatted.\n\n" \
    "\t${cyan}--pylint${reset}\t" \
    "Format python source files with pylint.\n" \
    "\t${cyan}--flake8${reset}\t" \
    "Format python source files with flake8.\n" \
    "\t${cyan}--c${reset}     \t" \
    "Format c source files with clangformat.\n" \
    "\t${cyan}--ctest${reset} \t" \
    "Check if c source files adhere to clangformat.\n"
  exit 0
}

function install() {
  NOMP_INSTALL_SUCCESS=false
  cmake --build "${NOMP_BUILD_DIR}" --target install &&
    NOMP_INSTALL_SUCCESS=true

  if [[ ${NOMP_INSTALL_SUCCESS} = true ]]; then
    echo "${green}Successfully installed libnomp${reset}"
    echo "See ${cyan}lnrun -h${reset} or ${cyan}lnrun --help${reset} for " \
      "available commands."

    [[ ${NOMP_DEFAULT_PROMPT} = "n" ]] && exit 0

    # Add nomp install dir to env
    NOMP_ENVIRONMENT=$(
      cat <<-END
# Setup nomp environment variables
export NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}
# Add lnrun script to path
export PATH=${NOMP_BIN_PATH}:\${PATH}
END
    )

    # set the libnomp env variables if not
    [[ ${NOMP_DEFAULT_PROMPT} = "y" ]] && update_bashrc
    read -p "Do you wish to add libnomp variables to .bashrc? [Y|n]: " -n 1
    echo
    [[ $REPLY =~ ^[Yy]$ ]] && update_bashrc
    exit 0
  else
    echo "${red}Failed to install libnomp${reset}"
    exit 1
  fi
}

function format() {
  NOMP_FORMAT_SUCCESS=false
  ${1} && NOMP_FORMAT_SUCCESS=true

  if [[ ${NOMP_FORMAT_SUCCESS} = true ]]; then
    echo "${green}Successfully formatted source files with ${1}${reset}"
  else
    echo "${red}Failed to format source file with ${1}${reset}"
    exit 1
  fi
}

if [ $# -eq 0 ]; then
  echo "No arguments were provided to ${cyan}lnmake${reset} script."
  exit 0
fi

if [[ $# -gt 0 ]]; then
  case $1 in
  i | install)
    shift
    if [[ $# -gt 0 ]]; then
      case $1 in
      h | help) print_help ;;
      -y | --yes) NOMP_DEFAULT_PROMPT="y" ;;
      -n | --no) NOMP_DEFAULT_PROMPT="n" ;;
      *)
        echo "${red}Invalid argument: ${1}${reset}."
        echo "See ${cyan}./${0} h|--help${reset} for the accepted commands."
        exit 1
        ;;
      esac
    fi
    install
    ;;
  f | format)
    shift
    NOMP_FORMAT_CMDS=()
    while [ $# -gt 0 ]; do
      case $1 in
      --pylint) NOMP_FORMAT_CMDS+=("${NOMP_SUPPORTED_FORMAT_CMDS[0]}") ;;
      --flake8) NOMP_FORMAT_CMDS+=("${NOMP_SUPPORTED_FORMAT_CMDS[1]}") ;;
      --c) NOMP_FORMAT_CMDS+=("${NOMP_SUPPORTED_FORMAT_CMDS[2]}") ;;
      --ctest) NOMP_FORMAT_CMDS+=("${NOMP_SUPPORTED_FORMAT_CMDS[3]}") ;;
      *)
        echo "${red}Invalid argument: ${1}${reset}"
        echo "See ${cyan}${0} h|help f|format ${reset} for the accepted commands."
        exit 1
        ;;
      esac
      shift
    done
    if [[ ${#NOMP_FORMAT_CMDS[@]} -eq 0 ]]; then
      for cmd in "${NOMP_SUPPORTED_FORMAT_CMDS[@]}"; do
        format "${cmd}"
      done
    else
      for cmd in "${NOMP_FORMAT_CMDS[@]}"; do
        format "${cmd}"
      done
    fi
    exit 0
    ;;
  h | help) print_help ;;
  *)
    echo "${red}Invalid argument: ${1}${reset}."
    echo "See ${cyan}./${0} h|--help${reset} for the accepted commands."
    exit 1
    ;;
  esac
fi
