[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 80

[tool.black]
line_length = 80
preview = true

[tool.pylint.format]
max-line-length = 80
