#if !defined(_LIB_NOMP_DEFS_H_)
#define _LIB_NOMP_DEFS_H_

#define NOMP_MAX_BUFFER_SIZE 128
#define NOMP_MAX_SRC_SIZE 16384
#define NOMP_MAX_CFLAGS_SIZE 16384
#define NOMP_MAX_KNL_ARGS_SIZE 64
#define NOMP_MAX_SCRATCH_SIZE (32768 * sizeof(double))

#define NOMP_DEFAULT_VERBOSE 1
#define NOMP_DEFAULT_PROFILE 0
#define NOMP_DEFAULT_DEVICE 0
#define NOMP_DEFAULT_PLATFORM 0

#endif // _LIB_NOMP_DEFS_H_
