#if !defined(_NOMP_LOG_STR_H_)
#define _NOMP_LOG_STR_H_

const char *const ERR_STR_NOMP_IS_ALREADY_INITIALIZED;
const char *const ERR_STR_FAILED_TO_INITIALIZE_NOMP;
const char *ERR_STR_FAILED_TO_FINALIZE_NOMP;
const char *ERR_STR_NOMP_INSTALL_DIR_NOT_SET;
const char *ERR_STR_NOMP_IS_NOT_INITIALIZED;

const char *ERR_STR_INVALID_MAP_OP;
const char *ERR_STR_INVALID_MAP_PTR;
const char *ERR_STR_PTR_IS_ALREADY_ALLOCATED;

const char *ERR_STR_KERNEL_RUN_FAILED;
const char *ERR_STR_INVALID_KERNEL;

const char *WARNING_STR_PYTHON_IS_ALREADY_INITIALIZED;
const char *ERR_STR_LOOPY_CONVERSION_ERROR;
const char *ERR_STR_USER_CALLBACK_NOT_FOUND;
const char *ERR_STR_USER_CALLBACK_FAILURE;
const char *ERR_STR_LOOPY_KNL_NAME_NOT_FOUND;
const char *ERR_STR_LOOPY_CODEGEN_FAILED;
const char *ERR_STR_LOOPY_GRIDSIZE_FAILED;
const char *ERR_STR_GRIDSIZE_CALCULATION_FAILED;
const char *ERR_STR_INVALID_KNL_ARG_TYPE;
const char *ERR_STR_INVALID_DEVICE;
const char *ERR_STR_KNL_ARG_SET_ERROR;
const char *ERR_STR_INVALID_PLATFORM;
const char *ERR_STR_MALLOC_ERROR;

#endif
