name: libnomp CI Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9, gcc-10, clang-10, clang-11, clang-12]
      fail-fast: false
    name: "${{ matrix.compiler }}"
    env:
      CC: ${{ matrix.compiler }}
      TESTDIR: tests
      BUILDDIR: build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install apt dependencies and set environment
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y pocl-opencl-icd opencl-headers
          pip3 install git+https://github.com/inducer/loopy
          pip3 install pycparser pyopencl
          echo "NOMP_INSTALL_DIR=${PWD}/install" >> $GITHUB_ENV

      - name: Build libnomp
        shell: bash
        run: |
          mkdir -p ${BUILDDIR}
          cd ${BUILDDIR}
          cmake -DCMAKE_INSTALL_PREFIX=../install -DOpenCL_LIBRARY=/lib/x86_64-linux-gnu/libOpenCL.so.1 ..
          make install

      - name: nomp-api
        shell: bash
        run: |
          cd ${TESTDIR}
          ./run-tests.sh
