name: Unit tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        # compiler: [gcc-9, gcc-10, clang-10, clang-11, clang-12]
        compiler: [gcc-10]
      fail-fast: false
    name: "${{ matrix.compiler }}"
    env:
      CC: ${{ matrix.compiler }}
      TESTDIR: tests
      BUILDDIR: build
    steps:
      - name: Setup Github actions
        uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.13
        if: ${{ inputs.debug_enabled }}
      - name: Setup conda environment "libnomp"
        id: setup_conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge, defaults
          channel-priority: true
          environment-file: environment.yml
          activate-environment: libnomp
          auto-activate-base: false
      - name: Install pocl
        id: install_pocl
        run: |
          conda install -c conda-forge pocl
      - name: Build libnomp
        id: build_libnomp
        run: |
          echo "NOMP_INSTALL_DIR=${PWD}/install" >> $GITHUB_ENV
          mkdir -p ${BUILDDIR}
          cd ${BUILDDIR}
          cmake -DCMAKE_INSTALL_PREFIX=../install \
            -DOpenCL_LIBRARY=${CONDA_PREFIX}/lib/libOpenCL.so \
            -DOpenCL_INCLUDE_DIR=${CONDA_PREFIX}/include ..
          make install
      - name: Run libnomp tests
        id: run_libnomp
        run: |
          cd ${TESTDIR}
          ./run-tests.sh
      - name: Block to allow inspecting failures
        run: sleep 30m
        if: ${{ failure() && inputs.debug_enabled }}
