name: libnomp CI Tests
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9, gcc-10, clang-10, clang-11, clang-12]
      fail-fast: false
    name: "${{ matrix.compiler }}"
    env:
      CC: ${{ matrix.compiler }}
      TESTDIR: tests
      BUILDDIR: build
    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y pocl-opencl-icd opencl-headers clinfo

      - name: Build libnomp
        shell: bash
        run: |
          mkdir -p ${BUILDDIR}
          cd ${BUILDDIR}
          cmake -DCMAKE_INSTALL_PREFIX=../install -DOpenCL_LIBRARY=/lib/x86_64-linux-gnu/libOpenCL.so.1 ..
          make install

      - name: Set environment
        shell: bash
        run: |
          echo "NOMP_INSTALL_DIR=${PWD}/install" >> $GITHUB_ENV

      - name: nomp-api
        shell: bash
        run: |
          ${TESTDIR}/run-tests.sh -g nomp-api -t ${BUILDDIR}

      - name: vec-init
        shell: bash
        run: |
          ${TESTDIR}/run-tests.sh -g vec-init -t ${BUILDDIR}

      - name: vec-add
        shell: bash
        run: |
          ${TESTDIR}/run-tests.sh -g vec-add -t ${BUILDDIR}
