name: pylint check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  # Increase to reset cache manually
  REQUIREMENTS_CACHE_NUMBER: 1
jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub actions
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ runner.os }}-build-requirements-${{ hashFiles('requirements.txt') }}-${{ env.REQUIREMENTS_CACHE_NUMBER }}
        id: requirements_cache
      - name: Install pip and packges in requirements.txt
        id: install_requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: (steps.requirements_cache.outputs.cache-hit != 'true')
      - name: Install pylint
        run: |
          pip install pylint
        if: (steps.requirements_cache.outputs.cache-hit != 'true')
      - name: Run pylint check
        run:
          pylint --fail-under=9.8 ./python
