name: python static checks
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  POCL_CACHE_NUMBER: 1
jobs:
  python-static-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      BUILDDIR: build
    steps:
      - name: Setup GitHub actions
        uses: actions/checkout@v3
      - name: Setup Mambaforge
        id: setup_conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: libnomp-dev
          use-mamba: true
      - name: Cache conda environment
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs/libnomp-dev
          key:  conda-${{ runner.os }}-${{ hashFiles('environment-dev.yml') }}-${{ hashFiles('requirements.txt') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Update environment
        id: update_env
        run: |
          mamba env update -n libnomp-dev -f environment-dev.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir/pocl
          key:  ${{ runner.os }}-build-pocl-${{ env.POCL_CACHE_NUMBER }}
        id: pocl_cache
      - name: Install pocl
        id: install_pocl
        run: |
          mamba install -c conda-forge pocl
        if: (steps.pocl_cache.outputs.cache-hit != 'true') || (steps.cache.outputs.cache-hit != 'true')
      - name: Generate Makefile
        id: generate_makefile
        run: |
          echo "NOMP_INSTALL_DIR=${PWD}/../install" >> $GITHUB_ENV
          ./lncfg -i ../install -o ${CONDA_PREFIX}/lib/libOpenCL.so
      - name: Run Pylint
        id: run_pylint
        run: |
          ./lnmake format --pylint
      - name: Run Flake8
        id: run_flake8
        run: |
          ./lnmake format --flake8
